[tool.isort]
balanced_wrapping = true
force_sort_within_sections = true

[tool.ruff]
fix = true
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "N",
    "ASYNC",
    "FBT",
    "B",
    "A",
    "C4",
    "DTZ",
    "EM",
    "EXE",
    "PIE",
    "SLOT",
    "SIM",
    "INT",
    "PTH",
    "TD",
    "PD",
    "PL",
    "TRY",
    "FLY",
    "NPY",
    "RUF",
]

[tool.black]
fast = true
check = true
workers = 4
skip-string-normalization = true
skip-magic-trailing-comma = true
