[tool.isort]
balanced_wrapping = true
force_sort_within_sections = true

[tool.ruff]
select = ["F", "E", "I", "UP", "N", "S", "B", "C4"]
fix = true

[tool.black]
fast = true
check = true
workers = 4
skip-string-normalization = true
skip-magic-trailing-comma = true
